name: 'Enhancement Request'
description: 'Request new work.'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: 'Write a summary of the request. List acceptance criteria, explain how you reached this solution, and if there are alternatives.'
  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Summary'
  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Acceptance Criteria'
  - type: markdown
    attributes:
      value: 'List all links helpful for others to understand your request.'
  - type: textarea
    attributes:
      label: 'Resource Links'
  - type: checkboxes
    attributes:
      label: 'Label'
      description: 'Please assign the proper label to describe this work by selecting it on the right. The options are: `development`, `automation`, `artifacts`, `documentation`, and `project-management`.'
      options:
        - label: 'I have assigned a proper work label to this issue.'
          required: true
  - type: checkboxes
    attributes:
      label: 'Project'
      description: 'Please assign this issue to a project.'
      options:
        - label: 'I have assigned this issue to a project.'
          required: true
