name: Create Release Tag

on:
  pull_request_target:
    types:
      - closed
    branches:
      - development

jobs:
  create:
    if: github.event.pull_request.merged
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.ACTION_CREATE_TAG_TOKEN }}
    - name: 'Get Latest Tag'
      id: get-latest-tag
      run: |
        export TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        export BUMP_INDEX=$([ "${{ vars.BUMP_TYPE }}" = "major" ] && echo "1" || ([ "${{ vars.BUMP_TYPE }}" = "minor" ] && echo "2" || echo "3"))
        echo "bump-index=$BUMP_INDEX" >> $GITHUB_OUTPUT
    - name: 'Increment Version Number'
      id: increment-version-number
      run: |
        export NUMBER_TO_BUMP=$(echo "${{ steps.get-latest-tag.outputs.tag }}" | cut -d "." -f ${{ steps.get-latest-tag.outputs.bump-index }})
        export NEW_VERSION_NUMBER=$(echo $NUMBER_TO_BUMP + 1 | bc)
        export OLD_MAJOR=$(echo "${{ steps.get-latest-tag.outputs.tag }}" | cut -d "." -f 1)
        export OLD_MINOR=$(echo "${{ steps.get-latest-tag.outputs.tag }}" | cut -d "." -f 2)
        export OLD_PATCH=$(echo "${{ steps.get-latest-tag.outputs.tag }}" | cut -d "." -f 3)
        export NEW_MAJOR=$([ "${{ vars.BUMP_TYPE }}" = "major" ] && echo "$NEW_VERSION_NUMBER" || echo "$OLD_MAJOR")
        export NEW_MINOR=$([ "${{ vars.BUMP_TYPE }}" = "minor" ] && echo "$NEW_VERSION_NUMBER" || echo "$OLD_MINOR")
        export NEW_PATCH=$([ "${{ vars.BUMP_TYPE }}" = "patch" ] && echo "$NEW_VERSION_NUMBER" || echo "$OLD_PATCH")
        echo "new-major=$NEW_MAJOR" >> $GITHUB_OUTPUT
        echo "new-minor=$NEW_MINOR" >> $GITHUB_OUTPUT
        echo "new-patch=$NEW_PATCH" >> $GITHUB_OUTPUT
    - name: Import GPG key
      run: echo "$GPG_KEY" | base64 --decode | gpg --batch --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
    - name: Setup git
      run: |
        git config --local user.email "${{ vars.GIT_CONFIG_EMAIL }}"
        git config --local user.name "${{ vars.GIT_CONFIG_NAME }}"
        git config --local user.signingkey "$GPG_KEY_ID"
        git config --local tag.gpgsign true
      env:
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
    - name: 'Create New Version Tag'
      run: |
        export NEW_TAG=$(echo "${{ steps.increment-version-number.outputs.new-major }}.${{ steps.increment-version-number.outputs.new-minor }}.${{ steps.increment-version-number.outputs.new-patch }}")
        git tag --annotate $NEW_TAG --sign --message "Generated by GitHub Action : Create Release Tag"
        git push --tags
        
    
